In [173]:
import numpy as np


# numpy array properties


In [174]:
# creating array with arange function of numpy
a = np.arange(15)  # single dimensional
print(a)
a = np.arange(15).reshape(3,5)  # multi dimensional
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [175]:
x = np.array([1,2,3,45,6])
print(x)
  


[ 1  2  3 45  6]


In [176]:
y = np.array([[1,2,3] , [2,3,4]])
print(y)

[[1 2 3]
 [2 3 4]]


In [177]:
print('shap:' , x.shape)
print('num of dimensions', x.ndim)
print('type of data', x.dtype)
print('Y')
print('shape:', y.shape)
print('num of dimensions', y.ndim)
print('type of data', x.dtype)

shap: (5,)
num of dimensions 1
type of data int32
Y
shape: (2, 3)
num of dimensions 2
type of data int32


 - arange
 - linspace
 - random.*
 - eye
 - ones
 - zeros

In [178]:
np.set_printoptions(precision=4, suppress=True)

In [179]:
a = np.arange(-10, 10, .2)
print(a)

[-10.   -9.8  -9.6  -9.4  -9.2  -9.   -8.8  -8.6  -8.4  -8.2  -8.   -7.8
  -7.6  -7.4  -7.2  -7.   -6.8  -6.6  -6.4  -6.2  -6.   -5.8  -5.6  -5.4
  -5.2  -5.   -4.8  -4.6  -4.4  -4.2  -4.   -3.8  -3.6  -3.4  -3.2  -3.
  -2.8  -2.6  -2.4  -2.2  -2.   -1.8  -1.6  -1.4  -1.2  -1.   -0.8  -0.6
  -0.4  -0.2  -0.    0.2   0.4   0.6   0.8   1.    1.2   1.4   1.6   1.8
   2.    2.2   2.4   2.6   2.8   3.    3.2   3.4   3.6   3.8   4.    4.2
   4.4   4.6   4.8   5.    5.2   5.4   5.6   5.8   6.    6.2   6.4   6.6
   6.8   7.    7.2   7.4   7.6   7.8   8.    8.2   8.4   8.6   8.8   9.
   9.2   9.4   9.6   9.8]


In [180]:
a = np.arange(-10, 10, .2)
print(a.shape)

(100,)


In [181]:
b = np.linspace(0, 1, 100)
print(b)

[0.     0.0101 0.0202 0.0303 0.0404 0.0505 0.0606 0.0707 0.0808 0.0909
 0.101  0.1111 0.1212 0.1313 0.1414 0.1515 0.1616 0.1717 0.1818 0.1919
 0.202  0.2121 0.2222 0.2323 0.2424 0.2525 0.2626 0.2727 0.2828 0.2929
 0.303  0.3131 0.3232 0.3333 0.3434 0.3535 0.3636 0.3737 0.3838 0.3939
 0.404  0.4141 0.4242 0.4343 0.4444 0.4545 0.4646 0.4747 0.4848 0.4949
 0.5051 0.5152 0.5253 0.5354 0.5455 0.5556 0.5657 0.5758 0.5859 0.596
 0.6061 0.6162 0.6263 0.6364 0.6465 0.6566 0.6667 0.6768 0.6869 0.697
 0.7071 0.7172 0.7273 0.7374 0.7475 0.7576 0.7677 0.7778 0.7879 0.798
 0.8081 0.8182 0.8283 0.8384 0.8485 0.8586 0.8687 0.8788 0.8889 0.899
 0.9091 0.9192 0.9293 0.9394 0.9495 0.9596 0.9697 0.9798 0.9899 1.    ]


In [182]:
np.random.random((3,3)) # random values b/w zero to one

array([[0.8033, 0.9484, 0.8594],
       [0.3324, 0.4386, 0.5996],
       [0.1859, 0.5391, 0.5181]])

In [183]:
np.random.randint(1, 1000, (3,3)) # random values b/w start and end

array([[380, 455, 233],
       [850,  17, 829],
       [648, 870, 841]])

In [184]:
np.eye (5, dtype=int) # identity matrix


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [185]:
np.rot90(np.eye (5, dtype=int)) # identity matrix




array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [186]:
np.ones((5,5), dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [187]:
np.zeros((5,5), dtype= int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# operations
- arthimatic
- statistical
- trigonometric
- logical
- slicing
- filtering
- sorting


In [188]:
x = np.random.randint(1,25, (2,3))
y = np.random.randint(1,25, (3,2))
print(x)
print(y)

[[20  3 16]
 [20  4 13]]
[[12  6]
 [ 7  4]
 [21 10]]


In [189]:
print("y transposed")
print(x + y.T)
print("x transposed + y")
print(x.T + y)

y transposed
[[32 10 37]
 [26  8 23]]
x transposed + y
[[32 26]
 [10  8]
 [37 23]]


In [190]:
print(" matrix multiplication elementwise")
print(x * y.T)
print(" matrix multiplication")
print(x @ y)

 matrix multiplication elementwise
[[240  21 336]
 [120  16 130]]
 matrix multiplication
[[597 292]
 [541 266]]


In [191]:
np.hstack((x,x,x,x,x))

array([[20,  3, 16, 20,  3, 16, 20,  3, 16, 20,  3, 16, 20,  3, 16],
       [20,  4, 13, 20,  4, 13, 20,  4, 13, 20,  4, 13, 20,  4, 13]])

In [192]:
np.vstack((x,x,y.T))

array([[20,  3, 16],
       [20,  4, 13],
       [20,  3, 16],
       [20,  4, 13],
       [12,  7, 21],
       [ 6,  4, 10]])

In [193]:
print("sum of all elements:" ,x.sum())
print("sum of all elements row wise:" ,x.sum(axis=1))
print("sum of all elements col wise:" ,x.sum(axis=0))
print("average of all elements:" ,x.mean())
print("median of all elements:" ,np.median(x))
print("min of all elements:", x.min())
print("max of all elements:", x.max())
print("std of all elements:", x.std())
print("variance of all elements:", x.var())
print("any item in non - zero:", x.any())
print("all item are non zero:",x.all())

sum of all elements: 76
sum of all elements row wise: [39 37]
sum of all elements col wise: [40  7 29]
average of all elements: 12.666666666666666
median of all elements: 14.5
min of all elements: 3
max of all elements: 20
std of all elements: 6.920179830675565
variance of all elements: 47.888888888888886
any item in non - zero: True
all item are non zero: True


In [194]:
print(np.pi)
print(np.nan)
print(np.inf)
print(np.e)

3.141592653589793
nan
inf
2.718281828459045


In [195]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))


[[ 0.9129  0.1411 -0.2879]
 [ 0.9129 -0.7568  0.4202]]
[[ 0.4081 -0.99   -0.9577]
 [ 0.4081 -0.6536  0.9074]]
[[ 2.2372 -0.1425  0.3006]
 [ 2.2372  1.1578  0.463 ]]


 # boolean filter


In [196]:
x[x > 5]

array([20, 16, 20, 13])

In [197]:
x = np.random.randint(-3,3, (5,5))
x


array([[-1, -2,  0,  2, -3],
       [-3,  1,  0, -3,  0],
       [-2,  2,  2, -1, -3],
       [-2, -3,  0,  1, -3],
       [-3, -2, -2, -1,  2]])

In [198]:
x[(x > -2) & (x < 2)]

array([-1,  0,  1,  0,  0, -1,  0,  1, -1])

# indexing and slicing

In [199]:
x[0, 0]

-1

In [200]:
x[3,3]

1

syntax for slicing in 1d: `[start:stop:step]`

syntax for slicing in 2d: `[rstart:rstop:rstep, cstart:cstop:cstep]`

In [201]:
x[0] # first row
x[-1] # last row
print(x[0,:3]) # first row first three elements
print(x[2, -4:]) # 2 index row last four elements


[-1 -2  0]
[ 2  2 -1 -3]


In [202]:
print(x[ :, 0]) # first column
print(x[:, -1 ]) # last column
print(x[:,:2]) # first two columns
print(x[:,[1,3]]) # first index and third index column
print(x[:, [2,4,1,3]]) # 2,4,1,3 index columns

[-1 -3 -2 -2 -3]
[-3  0 -3 -3  2]
[[-1 -2]
 [-3  1]
 [-2  2]
 [-2 -3]
 [-3 -2]]
[[-2  2]
 [ 1 -3]
 [ 2 -1]
 [-3  1]
 [-2 -1]]
[[ 0 -3 -2  2]
 [ 0  0  1 -3]
 [ 2 -3  2 -1]
 [ 0 -3 -3  1]
 [-2  2 -2 -1]]


# sorting

In [203]:
x = np.random.randint(1,100, (6,3))
x

array([[ 5,  2, 87],
       [40, 76, 40],
       [18, 80, 34],
       [17, 10, 77],
       [41, 95, 86],
       [60, 48, 39]])

In [204]:
x.sort(axis=1)
x

array([[ 2,  5, 87],
       [40, 40, 76],
       [18, 34, 80],
       [10, 17, 77],
       [41, 86, 95],
       [39, 48, 60]])

In [205]:
x = x.flatten()
x.sort()

In [206]:
x

array([ 2,  5, 10, 17, 18, 34, 39, 40, 40, 41, 48, 60, 76, 77, 80, 86, 87,
       95])

In [207]:
x.max()

95

In [208]:
x.argmax() # returns index of max element

17

In [209]:
x.argmin() # returns index of min element

0