In [3]:
import numpy as np


# numpy array properties


In [4]:
# creating array with arange function of numpy
a = np.arange(15)  # single dimensional
print(a)
a = np.arange(15).reshape(3,5)  # multi dimensional
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
x = np.array([1,2,3,45,6])
print(x)
  


[ 1  2  3 45  6]


In [6]:
y = np.array([[1,2,3] , [2,3,4]])
print(y)

[[1 2 3]
 [2 3 4]]


In [7]:
print('shap:' , x.shape)
print('num of dimensions', x.ndim)
print('type of data', x.dtype)
print('Y')
print('shape:', y.shape)
print('num of dimensions', y.ndim)
print('type of data', x.dtype)

shap: (5,)
num of dimensions 1
type of data int32
Y
shape: (2, 3)
num of dimensions 2
type of data int32


 - arange
 - linspace
 - random.*
 - eye
 - ones
 - zeros

In [8]:
np.set_printoptions(precision=4, suppress=True)

In [9]:
a = np.arange(-10, 10, .2)
print(a)

[-10.   -9.8  -9.6  -9.4  -9.2  -9.   -8.8  -8.6  -8.4  -8.2  -8.   -7.8
  -7.6  -7.4  -7.2  -7.   -6.8  -6.6  -6.4  -6.2  -6.   -5.8  -5.6  -5.4
  -5.2  -5.   -4.8  -4.6  -4.4  -4.2  -4.   -3.8  -3.6  -3.4  -3.2  -3.
  -2.8  -2.6  -2.4  -2.2  -2.   -1.8  -1.6  -1.4  -1.2  -1.   -0.8  -0.6
  -0.4  -0.2  -0.    0.2   0.4   0.6   0.8   1.    1.2   1.4   1.6   1.8
   2.    2.2   2.4   2.6   2.8   3.    3.2   3.4   3.6   3.8   4.    4.2
   4.4   4.6   4.8   5.    5.2   5.4   5.6   5.8   6.    6.2   6.4   6.6
   6.8   7.    7.2   7.4   7.6   7.8   8.    8.2   8.4   8.6   8.8   9.
   9.2   9.4   9.6   9.8]


In [10]:
a = np.arange(-10, 10, .2)
print(a.shape)

(100,)


In [11]:
b = np.linspace(0, 1, 100)
print(b)

[0.     0.0101 0.0202 0.0303 0.0404 0.0505 0.0606 0.0707 0.0808 0.0909
 0.101  0.1111 0.1212 0.1313 0.1414 0.1515 0.1616 0.1717 0.1818 0.1919
 0.202  0.2121 0.2222 0.2323 0.2424 0.2525 0.2626 0.2727 0.2828 0.2929
 0.303  0.3131 0.3232 0.3333 0.3434 0.3535 0.3636 0.3737 0.3838 0.3939
 0.404  0.4141 0.4242 0.4343 0.4444 0.4545 0.4646 0.4747 0.4848 0.4949
 0.5051 0.5152 0.5253 0.5354 0.5455 0.5556 0.5657 0.5758 0.5859 0.596
 0.6061 0.6162 0.6263 0.6364 0.6465 0.6566 0.6667 0.6768 0.6869 0.697
 0.7071 0.7172 0.7273 0.7374 0.7475 0.7576 0.7677 0.7778 0.7879 0.798
 0.8081 0.8182 0.8283 0.8384 0.8485 0.8586 0.8687 0.8788 0.8889 0.899
 0.9091 0.9192 0.9293 0.9394 0.9495 0.9596 0.9697 0.9798 0.9899 1.    ]


In [12]:
np.random.random((3,3)) # random values b/w zero to one

array([[0.3967, 0.2979, 0.083 ],
       [0.4546, 0.846 , 0.6066],
       [0.8895, 0.6615, 0.8648]])

In [13]:
np.random.randint(1, 1000, (3,3)) # random values b/w start and end

array([[384, 985, 301],
       [471, 619, 456],
       [361, 754, 261]])

In [14]:
np.eye (5, dtype=int) # identity matrix


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [15]:
np.rot90(np.eye (5, dtype=int)) # identity matrix




array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [16]:
np.ones((5,5), dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.zeros((5,5), dtype= int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# operations
- arthimatic
- statistical
- trigonometric
- logical
- slicing
- filtering
- sorting


In [18]:
x = np.random.randint(1,25, (2,3))
y = np.random.randint(1,25, (3,2))
print(x)
print(y)

[[ 5 21 24]
 [ 6 11 16]]
[[23  5]
 [20 15]
 [ 1  7]]


In [19]:
print("y transposed")
print(x + y.T)
print("x transposed + y")
print(x.T + y)

y transposed
[[28 41 25]
 [11 26 23]]
x transposed + y
[[28 11]
 [41 26]
 [25 23]]


In [20]:
print(" matrix multiplication elementwise")
print(x * y.T)
print(" matrix multiplication")
print(x @ y)

 matrix multiplication elementwise
[[115 420  24]
 [ 30 165 112]]
 matrix multiplication
[[559 508]
 [374 307]]


In [21]:
np.hstack((x,x,x,x,x))

array([[ 5, 21, 24,  5, 21, 24,  5, 21, 24,  5, 21, 24,  5, 21, 24],
       [ 6, 11, 16,  6, 11, 16,  6, 11, 16,  6, 11, 16,  6, 11, 16]])

In [26]:
np.vstack((x,x,y.T))

array([[ 5, 21, 24],
       [ 6, 11, 16],
       [ 5, 21, 24],
       [ 6, 11, 16],
       [23, 20,  1],
       [ 5, 15,  7]])

In [30]:
print("sum of all elements:" ,x.sum())
print("sum of all elements row wise:" ,x.sum(axis=1))
print("sum of all elements col wise:" ,x.sum(axis=0))
print("average of all elements:" ,x.mean())
print("median of all elements:" ,np.median(x))
print("min of all elements:", x.min())
print("max of all elements:", x.max())
print("std of all elements:", x.std())
print("variance of all elements:", x.var())
print("any item in non - zero:", x.any())
print("all item are non zero:",x.all())

sum of all elements: 83
sum of all elements row wise: [50 33]
sum of all elements col wise: [11 32 40]
average of all elements: 13.833333333333334
median of all elements: 13.5
min of all elements: 5
max of all elements: 24
std of all elements: 7.151145984308312
variance of all elements: 51.13888888888889
any item in non - zero: True
all item are non zero: True


In [27]:
print(np.pi)
print(np.nan)
print(np.inf)
print(np.e)

3.141592653589793
nan
inf
2.718281828459045


In [28]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))


[[-0.9589  0.8367 -0.9056]
 [-0.2794 -1.     -0.2879]]
[[ 0.2837 -0.5477  0.4242]
 [ 0.9602  0.0044 -0.9577]]
[[  -3.3805   -1.5275   -2.1349]
 [  -0.291  -225.9508    0.3006]]
